server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone: http://eurea.instance.hotame:{eureka.instance.hostname}:eureka.instance.hostname:{server.port}/eureka/
